In [8]:
#1-Vektörler tek boyutlu,matrisler çift boyutludur.

SyntaxError: invalid syntax (<ipython-input-8-175d1c90dd01>, line 1)

In [9]:
#2
import numpy as np 

a = np.array([1,2,3,4,5,6,7,8,9,10])
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#3
b=np.zeros((10,10), dtype = int)
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
#4
c=np.ones((10,10))
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
#5
d=np.full((10,10),9)   
d

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [13]:
#6
e=np.arange(5,25,3)
e

array([ 5,  8, 11, 14, 17, 20, 23])

In [14]:
#7
f=np.linspace(-1,1,30) 
f

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [15]:
#8
g=np.random.randint(0,30, (5,6)) 
g

array([[10, 15, 24,  8, 27, 23],
       [28, 22, 28, 20,  1,  1],
       [25,  1, 28, 21,  5, 22],
       [ 6, 14, 18, 13, 26, 27],
       [19, 10, 16, 14, 29,  7]])

In [16]:
#9
h=np.eye(10) 
h

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
#10
ı=np.random.randint(0,10, (5,10)) 
ı
ı.size #eleman sayisi

50

In [18]:
ı.ndim #boyut bilgisini/sayisi

2

In [19]:
ı.shape #satir X sutun bilgisi

(5, 10)

In [20]:
ı.dtype #veri tipi

dtype('int32')

In [21]:
#11
j = np.random.randint(10, size = (3,4, 7))
j

array([[[6, 5, 6, 9, 8, 4, 2],
        [7, 4, 8, 0, 6, 5, 5],
        [1, 4, 4, 7, 2, 3, 6],
        [0, 8, 9, 0, 7, 5, 7]],

       [[3, 7, 5, 2, 9, 7, 5],
        [5, 1, 1, 4, 7, 3, 8],
        [2, 3, 8, 2, 9, 8, 7],
        [3, 5, 3, 6, 4, 2, 5]],

       [[4, 1, 7, 7, 6, 5, 0],
        [6, 0, 1, 5, 5, 7, 0],
        [8, 3, 7, 1, 0, 5, 3],
        [9, 2, 4, 7, 3, 6, 6]]])

In [22]:
#12
k=np.arange(1,10)
k.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#13
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
t = np.array([10,11,12])
np.concatenate([x,y,z,t])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
#14
a = np.array([[11],
              [11]])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])
np.hstack([a,b])  

array([[11,  9,  8,  7],
       [11,  6,  5,  4]])

In [25]:
#15
axis=1 --> birlestirme islemini yatay (sütun) olarak yapar.
axis=0 --> birlestirme islemini dikey (satır) olarak yapar.

SyntaxError: invalid syntax (<ipython-input-25-a1406ca815af>, line 2)

In [26]:
#16
a = np.array([1, 2, 3])

b = np.array([[15, 8, 7], 
              [19, 5, 4]])
np.vstack([a,b]) 

array([[ 1,  2,  3],
       [15,  8,  7],
       [19,  5,  4]])

In [27]:
a = np.array([[11],
              [11]])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])
np.hstack([a,b])  

array([[11,  9,  8,  7],
       [11,  6,  5,  4]])

In [28]:
#17
x=np.array([1,2,3,4,5,6,7,8,9,10])
np.split(x, [3,6,9])  

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10])]

In [29]:
#18
m=np.random.randint(0,30,(3))
m


array([13, 25, 20])

In [30]:
np.sort(m) 

array([13, 20, 25])

In [31]:
m[0]

13

In [32]:
m[1]

25

In [33]:
m[2]

20

In [34]:
#19
n=np.random.randint(10, size = 20)
n

array([4, 0, 3, 9, 5, 5, 9, 2, 1, 2, 4, 8, 0, 1, 7, 0, 7, 5, 3, 5])

In [35]:
n[3]

9

In [36]:
n[5]

5

In [37]:
n[7]

2

In [38]:
#20
n=np.random.randint(10, size = 10)
n

array([8, 5, 9, 1, 4, 7, 6, 4, 0, 7])

In [39]:
n[4]=44

In [40]:
n

array([ 8,  5,  9,  1, 44,  7,  6,  4,  0,  7])

In [ ]:
#21
#Diagonal Matrix and Trace Matrix
Diagonal Matrix:Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır olan matristir.
Trace Matrix:Bir kare matrisin tüm köşegen elemanlarının toplamıdır.

In [41]:
#22
x = np.diag([1, 2, 3, 4, 5])
x
#np.eye(5) kösegenleri 1 olan dioganel matris 

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [42]:
x[0,0],x[1,1],x[2,2],x[3,3],x[4,4]

(1, 2, 3, 4, 5)

In [43]:
#23
n=np.random.randint(10,20,(5))
n

array([16, 10, 18, 16, 18])

In [44]:
n[3:]

array([16, 18])

In [45]:
#24
ı=np.random.randint(0,10, (10,10)) 
ı

array([[4, 8, 4, 6, 7, 8, 4, 8, 2, 7],
       [8, 6, 1, 5, 9, 5, 0, 9, 2, 7],
       [9, 4, 9, 4, 0, 8, 4, 8, 4, 2],
       [6, 1, 4, 6, 3, 4, 3, 1, 3, 2],
       [9, 4, 3, 6, 9, 0, 2, 4, 6, 7],
       [8, 1, 3, 1, 4, 2, 8, 2, 9, 6],
       [0, 8, 9, 0, 8, 0, 7, 5, 7, 9],
       [8, 4, 6, 9, 3, 4, 3, 6, 7, 4],
       [4, 9, 5, 9, 3, 5, 6, 2, 7, 9],
       [2, 6, 8, 4, 0, 1, 4, 7, 1, 8]])

In [46]:
ı[2,4]

0

In [47]:
#a
ı[:,4]

array([7, 9, 0, 3, 9, 4, 8, 3, 3, 0])

In [48]:
#b
ı[1,:]

array([8, 6, 1, 5, 9, 5, 0, 9, 2, 7])

In [49]:
#c
ı[1:6,:]

array([[8, 6, 1, 5, 9, 5, 0, 9, 2, 7],
       [9, 4, 9, 4, 0, 8, 4, 8, 4, 2],
       [6, 1, 4, 6, 3, 4, 3, 1, 3, 2],
       [9, 4, 3, 6, 9, 0, 2, 4, 6, 7],
       [8, 1, 3, 1, 4, 2, 8, 2, 9, 6]])

In [50]:
#d
ı[2:5,3:7]

array([[4, 0, 8, 4],
       [6, 3, 4, 3],
       [6, 9, 0, 2]])

In [51]:
#e
ı[5:,:4]

array([[8, 1, 3, 1],
       [0, 8, 9, 0],
       [8, 4, 6, 9],
       [4, 9, 5, 9],
       [2, 6, 8, 4]])

In [52]:
#f
ı[:,(3,6,9)]

array([[6, 4, 7],
       [5, 0, 7],
       [4, 4, 2],
       [6, 3, 2],
       [6, 2, 7],
       [1, 8, 6],
       [0, 7, 9],
       [9, 3, 4],
       [9, 6, 9],
       [4, 4, 8]])

In [53]:
#g
ı[5,5]=1996

In [54]:
ı

array([[   4,    8,    4,    6,    7,    8,    4,    8,    2,    7],
       [   8,    6,    1,    5,    9,    5,    0,    9,    2,    7],
       [   9,    4,    9,    4,    0,    8,    4,    8,    4,    2],
       [   6,    1,    4,    6,    3,    4,    3,    1,    3,    2],
       [   9,    4,    3,    6,    9,    0,    2,    4,    6,    7],
       [   8,    1,    3,    1,    4, 1996,    8,    2,    9,    6],
       [   0,    8,    9,    0,    8,    0,    7,    5,    7,    9],
       [   8,    4,    6,    9,    3,    4,    3,    6,    7,    4],
       [   4,    9,    5,    9,    3,    5,    6,    2,    7,    9],
       [   2,    6,    8,    4,    0,    1,    4,    7,    1,    8]])

In [55]:
#25
x=np.arange(0,50,5) 
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [56]:
#a
x>20 #5tane

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
#b
x<30 #6tane

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [58]:
#c
x == 33 

array([False, False, False, False, False, False, False, False, False,
       False])

In [59]:
#d
x*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [60]:
#e
x%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [61]:
#26
a=np.random.randint(100, size = 50) 
a

array([33, 50, 73, 14, 12, 89, 84, 54, 79, 96, 80, 20,  9, 11,  6, 81,  3,
       91, 84,  8,  2, 16, 98, 81, 67, 60, 98, 20, 77, 73, 77, 99, 71, 74,
       44, 75, 88, 63, 91, 33, 34, 87, 57, 98, 34, 15, 15, 39, 10, 59])

In [62]:
np.mean(a)

54.64

In [63]:
#a
np.std(a)

32.02921166685187

In [64]:
#b
np.var(a)

1025.8704

In [65]:
#c
np.median(a)

61.5

In [66]:
#d
np.min(a)

2

In [67]:
#e
np.max(a)

99

In [68]:
#27
pandas serileri,herhangi bir veri türünü (tamsayılar, dizeler, kayan nokta sayıları, Python nesneleri vb.) tutabilen tek boyutlu etiketli bir arraydir.
numpy arrayleri ise tek veri türüne çevirerek tutar.

SyntaxError: invalid syntax (<ipython-input-68-af892a6278bd>, line 2)

In [69]:
#28
import pandas as pd
seri3 = pd.Series(["k",5,0.9,None,2],index = ("A","B","C","D","E"))    
seri3

A       k
B       5
C     0.9
D    None
E       2
dtype: object

In [70]:
#29
sozluk = { "Turkey" : "İstanbul", "Greece" : "Athens", "Kosovo" : "Priştine","Netherlands":"Amsterdam" ,"France":"Paris",}    #sozluk uzerinden index atayacagiz.
sozluk

{'Turkey': 'İstanbul',
 'Greece': 'Athens',
 'Kosovo': 'Priştine',
 'Netherlands': 'Amsterdam',
 'France': 'Paris'}

In [71]:
seri5 = pd.Series(sozluk)
seri5

Turkey          İstanbul
Greece            Athens
Kosovo          Priştine
Netherlands    Amsterdam
France             Paris
dtype: object

In [72]:
#30
y=np.random.randint(1,20,(10))
y

array([17,  9, 15,  6, 19, 10,  8,  9,  6,  8])

In [73]:
seri6 = pd.Series(y,index = ('a','b','c','d','e','f','g','h','ı','j'))
seri6

a    17
b     9
c    15
d     6
e    19
f    10
g     8
h     9
ı     6
j     8
dtype: int32

In [74]:
seri6["c"]

15

In [75]:
seri6[1]

9

In [76]:
seri6[[2,7]]

c    15
h     9
dtype: int32

In [77]:
seri6["b":"h"] 

b     9
c    15
d     6
e    19
f    10
g     8
h     9
dtype: int32

In [78]:
seri6[4:]

e    19
f    10
g     8
h     9
ı     6
j     8
dtype: int32

In [86]:
#31
seri2 = pd.Series(["Ahmet","Mehmet",3, 4.6, None, " "])
seri2

0     Ahmet
1    Mehmet
2         3
3       4.6
4      None
5          
dtype: object

In [87]:
seri1 = pd.Series([10,20,30,40])  
seri1

0    10
1    20
2    30
3    40
dtype: int64

In [93]:
seri = pd.concat([seri2,seri1], ignore_index=True) 
seri

0     Ahmet
1    Mehmet
2         3
3       4.6
4      None
5          
6        10
7        20
8        30
9        40
dtype: object

In [94]:
seri.iloc[[4,5,6]] 

4    None
5        
6      10
dtype: object

In [95]:
seri.loc[[4,5,6]]

4    None
5        
6      10
dtype: object

In [99]:
#Master odev 
a=np.random.random((4,4))
b=np.random.random((4,4))
a,b

(array([[0.24322967, 0.24755703, 0.41584721, 0.39131535],
        [0.62166242, 0.02233934, 0.4663003 , 0.31530105],
        [0.28957661, 0.5126004 , 0.9621094 , 0.18034143],
        [0.81142171, 0.68457677, 0.02266118, 0.72812526]]),
 array([[0.73222408, 0.79618226, 0.2444213 , 0.72877097],
        [0.44613749, 0.91274332, 0.75966616, 0.40287202],
        [0.72771738, 0.08454736, 0.71634855, 0.12462599],
        [0.37133163, 0.94218236, 0.22437472, 0.29888383]]))

In [119]:
list=[]
a=np.random.random((4,4))
b=np.random.random((4,4))
x=a-b
y=np.diag(x)
for i in y:
    if i<1 and i>-1:
        print(i)
        print(x)
        break
    else:
        continue

0.013269107520897383
[[ 0.01326911 -0.00991971 -0.13779949 -0.52785363]
 [ 0.16063435  0.42581332 -0.20068449 -0.21917554]
 [-0.01536202  0.12206879 -0.04727413 -0.65374372]
 [ 0.47439186  0.72664949 -0.59905239 -0.07828423]]
