### 1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

* Tek boyutlu Numpy arraylerine vektor, cok boyutlu Numpy arraylerine matris denir.

### 2. 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [1]:
import numpy as np
a = [i for i in range(10)]
a = np.array(a)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [2]:
zeros = np.zeros((10,10),dtype=int)
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [3]:
ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [4]:
nines = np.full((10,10),9,dtype=int)
nines

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

### 6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [5]:
numbers = np.arange(5,25,3)
numbers

array([ 5,  8, 11, 14, 17, 20, 23])

### 7. -1 ile 1 arasinda 30 adet Array olusturunuz.

In [6]:
array = np.linspace(-1,1,30)
array

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

### 8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [7]:
shape = np.random.randint(0,30,size=(5,6))
shape

array([[ 2,  6, 15,  8, 17, 28],
       [ 2, 14, 22,  7,  6, 24],
       [10, 24, 28,  4, 26, 25],
       [ 0, 17, 27, 23,  1, 20],
       [13, 11,  9, 16,  2,  1]])

### 9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 

In [8]:
eye = np.eye(10,dtype=int)
eye

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

### 10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
* a. eleman sayisini 
* b. boyut bilgisini/sayisini 
* c. satir X sutun bilgisini 
* d. veri tipini numpy metodlariyla yazdiriniz.

In [9]:
rand = np.random.randint(0,10,size = (5,10))
print('a.',rand.size)
print('b.',rand.ndim)
print('c.',rand.shape)
print('d.',rand.dtype)
print(rand)

a. 50
b. 2
c. (5, 10)
d. int64
[[1 0 0 5 6 4 9 7 8 7]
 [0 7 8 1 1 2 3 0 2 4]
 [2 4 7 2 4 0 2 5 2 9]
 [9 1 9 4 6 4 4 1 6 3]
 [9 9 4 4 0 6 5 2 6 1]]


### 11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [10]:
matris = np.random.randint(0,10,size=(3,4,7))
matris

array([[[4, 2, 9, 8, 7, 6, 9],
        [5, 3, 7, 5, 9, 5, 0],
        [9, 6, 9, 5, 8, 5, 8],
        [3, 3, 4, 4, 2, 9, 6]],

       [[8, 7, 9, 7, 0, 9, 0],
        [9, 7, 2, 5, 6, 0, 4],
        [6, 1, 7, 3, 1, 1, 5],
        [0, 0, 3, 6, 0, 6, 9]],

       [[5, 3, 8, 2, 6, 1, 2],
        [6, 6, 6, 7, 2, 8, 0],
        [5, 7, 5, 5, 2, 5, 5],
        [6, 8, 5, 7, 2, 3, 2]]])

### 12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [11]:
vector = np.arange(0,9)
vector = vector.reshape(3,3)
vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [12]:
a1 = np.array([i for i in range(1,5)])
a2 = np.array([i for i in range(5,10)])
a3 = np.array([i for i in range(10,15)])
a4 = np.array([i for i in range(15,20)])
np.concatenate([a1,a2,a3,a4])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### 14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [13]:
vector = np.array([[2],[6]])
matris = np.array([[2,4],[5,10]])
np.hstack([vector,matris])

array([[ 2,  2,  4],
       [ 6,  5, 10]])

### 15. Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

axis = 0 is for column, axis = 1 is for row.

### 16. Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

In [14]:
first = np.array([[1,1],[2,2]])
second = np.array([[4,5,6],[7,8,9]])
print(np.hstack([first,second]))
first = np.array([[1,1],[2,2]])
second = np.array([[4,5],[7,8]])
print(np.vstack([second,first]))

[[1 1 4 5 6]
 [2 2 7 8 9]]
[[4 5]
 [7 8]
 [1 1]
 [2 2]]


### 17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [15]:
liste = [i for i in range(10)]
np.split(liste,[2,4,6,8])

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

### 18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz. Sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.



In [16]:
random = np.random.randint(1,30,size=10)
random = np.sort(random)
for i in range(len(random)):
    print(str(i)+'. index',random[::-1][i])

0. index 26
1. index 23
2. index 21
3. index 9
4. index 9
5. index 7
6. index 5
7. index 4
8. index 3
9. index 1


### 19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [17]:
random = np.random.randint(1,100,20,int)
print(random)
print('Third: ',random[2],'\nFifth: ',random[4],'\nSeventh: ',random[6])


[58 36 47  2 91  4 22 76 34 73 76 77 72 92 44 96 19 40 64 52]
Third:  47 
Fifth:  91 
Seventh:  22


### 20. 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [18]:
random = np.random.randint(1,100,10,int)
print(random)
random[3] = 1000
print(random)

[12 82  8 36 46 25 83 69 15 63]
[  12   82    8 1000   46   25   83   69   15   63]


### 21. “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

* Diagonal Matrix kosegeni degerleri disindaki degerlerin 0 oldugu kare matrixdir. (1x1, 2x2, 3x3 ...)
* Trace Matrix kare matrixinin kose degerlerin toplanmasiyla elde edilen degerdir.

### 22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [19]:
random = np.random.randint(1,100,25,int).reshape(5,5)
print(random)
print(*[random[i,i] for i in range(5)],sep='\n')

[[75 39 94 54 38]
 [64 94 15 90 17]
 [80 95 61 28 68]
 [53 11 78 17  5]
 [60 48  1 66 73]]
75
94
61
17
73


### 23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [20]:
values = np.arange(11,20)
print(values)
print(values[3:])

[11 12 13 14 15 16 17 18 19]
[14 15 16 17 18 19]


### 24. 10X10 luk bir matris olusturunuz ve 3.satirin 5.sutununa ulasiniz. Ayrica;
* a. 5.sutunun tum satirlarina ulasiniz. 
* b. Tum sutunlarin 2.satirlarina ulasiniz. 
* c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
* d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
* e. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
* f. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
* g. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [21]:
random = np.random.randint(1,100,100,int).reshape(10,10)
print(random[2,4])
print('a: 4. column', random[:,4])
print('b: ',random[1,:])
print('c: ',random[1:7,:])
print('d: ',random[2:5,3:7])
print('e: ',random[5:,:4])
print('f: ',random[:,(2,5,8)])
random[4,4] = 1995
print(random[4,4])
print(random)

33
a: 4. column [54 95 33 29 23 64 17  2 71 10]
b:  [57 16 50 88 95 93 92  7 45 79]
c:  [[57 16 50 88 95 93 92  7 45 79]
 [70  2 91 34 33 74 11 19 87 76]
 [81 73 65 32 29 18 77 64 67 16]
 [42 90 35 26 23 91 97 91 86 47]
 [ 6 27 72 79 64 47 95 74 74 84]
 [45  5 89 56 17 16 90 52 77 18]]
d:  [[34 33 74 11]
 [32 29 18 77]
 [26 23 91 97]]
e:  [[ 6 27 72 79]
 [45  5 89 56]
 [ 5 92 44  9]
 [29 85 25 61]
 [21 11  3 98]]
f:  [[57 45 23]
 [50 93 45]
 [91 74 87]
 [65 18 67]
 [35 91 86]
 [72 47 74]
 [89 16 77]
 [44 40  2]
 [25 28 98]
 [ 3  4 57]]
1995
[[   9   50   57   85   54   45   97   63   23   75]
 [  57   16   50   88   95   93   92    7   45   79]
 [  70    2   91   34   33   74   11   19   87   76]
 [  81   73   65   32   29   18   77   64   67   16]
 [  42   90   35   26 1995   91   97   91   86   47]
 [   6   27   72   79   64   47   95   74   74   84]
 [  45    5   89   56   17   16   90   52   77   18]
 [   5   92   44    9    2   40   66   66    2   64]
 [  29   85   25   61   71   

### 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz (tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

* a. 20 den buyuk olan kac deger var. 
* b. 30’dan kucuk kac deger var 
* c. icerisinde 33 gecen kac deger var 
* d. olusturulan arrayin tum elemanlarini 5 ile carpin. 
* e. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [22]:
array = np.arange(0,50,5)
print(array)
print('a: ',(array>20).sum())
print('b: ',(array<30).sum())
print('c: ',(array==33).sum())
print('d: ',(array*5))
print('f: ',(array%2))

[ 0  5 10 15 20 25 30 35 40 45]
a:  5
b:  6
c:  0
d:  [  0  25  50  75 100 125 150 175 200 225]
f:  [0 1 0 1 0 1 0 1 0 1]


### 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve ortalamasini aliniz. Ayrica;
* a. standart sapmasini aliniz. 
* b. varyansini aliniz. 
* c. median’ini aliniz. 
* d. en kucuk degeri bulunuz. 
* e. en buyuk degeri bulunuz.

In [23]:
random = np.linspace(0,1,50)
print(np.mean(random))
print(np.std(random))
print(np.var(random))
print(np.median(random))
print(np.min(random))
print(np.max(random))
print(random)

0.5
0.2945075446869757
0.086734693877551
0.5
0.0
1.0
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


### 27.	Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

* Pandas serilerinde index sutunu bulunur. Defaulti 0 dan baslar n-1'e kadar devam eder.

### 28.	Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

In [24]:
import pandas as pd
series = pd.Series([1,'A',True,None,15],index=('A','B','C','D','E'))
series

A       1
B       A
C    True
D    None
E      15
dtype: object

### 29.	Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

In [25]:
dictionary = {"Netherlands":'Amsterdam', "Greece":'Athens', "Sweden":'Stockholm', "Spain":'Madrid', "Turkey":'Ankara'}
series = pd.Series(dictionary)
series

Netherlands    Amsterdam
Greece            Athens
Sweden         Stockholm
Spain             Madrid
Turkey            Ankara
dtype: object

### 30.	10 elemanli random bir vektor olusturun.
* Vektoru seriye cevirip indexleri str olarak belirleyin. 
(ornek: a,b,c,d,e,f,g.. seklinde)
* Index ismine gore serinin 3. elemanina ulasin. 
(ornek: c indexine karsilik gelen deger)
* Serinin index sirasina gore 1. Elamanina ulasin.
* Index ismine gore serinin  2. Ve 7. Elemanlarina ayni anda ulasin. 
(Ornek: b ve g indexine karsilik gelen degerler)
* Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin.
(Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
* Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

In [26]:
random = np.random.randint(1,100,10)
print(random)
random = pd.Series(random,index=('A','B','C','D','E','F','G','H','I','J'))
print(random)
print(random['C'])
print(random[0])
print(random[['B','G']])
print(random['B':'G'])
print(random[3:])

[34 65 56 15  9 37 32 43  2 75]
A    34
B    65
C    56
D    15
E     9
F    37
G    32
H    43
I     2
J    75
dtype: int64
56
34
B    65
G    32
dtype: int64
B    65
C    56
D    15
E     9
F    37
G    32
dtype: int64
D    15
E     9
F    37
G    32
H    43
I     2
J    75
dtype: int64


### 31.	2 adet 5 elemanli seri olusturun.
* Olusturdugunuz serileri birlestirin.
* Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
* Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

In [27]:
first = pd.Series(np.random.randint(1,5,5))
second = pd.Series(np.random.randint(1,5,5))
concat = pd.concat([first,second],ignore_index=True)
print(concat)
print(concat.loc['4':'6'])
print(concat.iloc[4:7])

0    1
1    3
2    4
3    3
4    4
5    4
6    1
7    1
8    3
9    4
dtype: int64
4    4
5    4
6    1
dtype: int64
4    4
5    4
6    1
dtype: int64


### Master odev ;
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz. 
* Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz. 
(Matris uretme islemini np.random.random((a,b)) fonksiyonu ile yapabilirsiniz. 0-1 arasi istenen boyutlarda array uretir.)

In [28]:
import time
count = 0
start_time = time.time()
while True:
    count+=1
    first = np.random.rand(10,10)
    second = np.random.rand(10,10)
    diagonal = np.diag(first-second)
    if len(list(filter(lambda x: x>-0.1 and x<0.1,diagonal)))==10:
        break
print(diagonal)
print('Counter: ',count)
print('Duration: ',time.time()-start_time)

[ 0.08950703  0.00607707 -0.07044478  0.02181793 -0.08499531 -0.08209982
  0.06090478  0.09119324  0.04435777  0.01343671]
Counter:  19493232
Duration:  251.33008980751038
