### 1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

### 2. 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [3]:
import numpy as np
a = [i for i in range(10)]
a = np.array(a)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [10]:
zeros = np.zeros((10,10),dtype=int)
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [11]:
ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [13]:
nines = np.full((10,10),9,dtype=int)
nines

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

### 6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [15]:
numbers = np.arange(5,25,3)
numbers

array([ 5,  8, 11, 14, 17, 20, 23])

### 7. -1 ile 1 arasinda 30 adet Array olusturunuz.

In [21]:
array = np.linspace(-1,1,30)
array

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

### 8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [38]:
shape = np.random.randint(0,30,size=(5,6))
shape

array([[19,  0, 21, 10, 11, 17],
       [15,  2, 12, 11, 13, 18],
       [29,  0, 26, 10,  0, 11],
       [ 5,  8, 10, 16, 12,  6],
       [ 0, 29,  3, 21,  6, 25]])

### 9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 

In [36]:
eye = np.eye(10,dtype=int)
eye

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

### 10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
* a. eleman sayisini 
* b. boyut bilgisini/sayisini 
* c. satir X sutun bilgisini 
* d. veri tipini numpy metodlariyla yazdiriniz.

In [42]:
rand = np.random.randint(0,10,size = (5,10))
print('a.',rand.size)
print('b.',rand.ndim)
print('c.',rand.shape)
print('d.',rand.dtype)
print(rand)

a. 50
b. 2
c. (5, 10)
d. int64
[[7 5 0 1 8 7 2 1 5 6]
 [4 4 2 3 0 3 7 3 6 6]
 [3 4 2 2 1 3 9 1 5 0]
 [1 2 2 3 5 4 5 7 3 2]
 [6 5 2 7 1 6 2 3 3 5]]


### 11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [44]:
matris = np.random.randint(0,10,size=(3,4,7))
matris

array([[[5, 2, 9, 5, 7, 6, 6],
        [1, 6, 1, 4, 3, 8, 5],
        [2, 4, 4, 0, 8, 9, 3],
        [9, 4, 0, 0, 7, 7, 8]],

       [[1, 0, 9, 6, 5, 3, 9],
        [2, 7, 1, 5, 0, 2, 8],
        [5, 5, 7, 1, 0, 8, 1],
        [8, 3, 3, 0, 4, 0, 0]],

       [[3, 4, 2, 0, 4, 1, 6],
        [6, 6, 0, 6, 7, 4, 0],
        [0, 5, 2, 5, 8, 6, 0],
        [1, 9, 3, 5, 5, 3, 9]]])

### 12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [49]:
vector = np.arange(0,9)
vector = vector.reshape(3,3)
vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [51]:
a1 = np.array([i for i in range(1,5)])
a2 = np.array([i for i in range(5,10)])
a3 = np.array([i for i in range(10,15)])
a4 = np.array([i for i in range(15,20)])
np.concatenate([a1,a2,a3,a4])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### 14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [54]:
vector = np.array([[2],[6]])
matris = np.array([[2,4],[5,10]])
np.hstack([vector,matris])

array([[ 2,  2,  4],
       [ 6,  5, 10]])

### 15. Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

axis = 0 is for column, axis = 1 is for row.

### 16. Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

In [58]:
first = np.array([[1,1],[2,2]])
second = np.array([[4,5,6],[7,8,9]])
print(np.hstack([first,second]))
first = np.array([[1,1],[2,2]])
second = np.array([[4,5],[7,8]])
print(np.vstack([second,first]))

[[1 1 4 5 6]
 [2 2 7 8 9]]
[[4 5]
 [7 8]
 [1 1]
 [2 2]]


### 17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [61]:
liste = [i for i in range(10)]
np.split(liste,[2,4,6,8])

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

### 18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz. Sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.



In [71]:
random = np.random.randint(1,30,size=10)
random = np.sort(random)
for i in range(len(random)):
    print(str(i)+'. index',random[::-1][i])

0. index 29
1. index 25
2. index 24
3. index 22
4. index 16
5. index 15
6. index 10
7. index 9
8. index 5
9. index 3


### 19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

### 20. 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

### 21. “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

### 22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

### 23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

### 24. 10X10 luk bir matris olusturunuz ve 3.satirin 5.sutununa ulasiniz. Ayrica;
* a. 5.sutunun tum satirlarina ulasiniz. 
* b. Tum sutunlarin 2.satirlarina ulasiniz. 
* c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
* d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
* e. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
* f. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
* g. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

### 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz (tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

* a. 20 den buyuk olan kac deger var. 
* b. 30’dan kucuk kac deger var 
* c. icerisinde 33 gecen kac deger var 
* d. olusturulan arrayin tum elemanlarini 5 ile carpin. 
* e. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

### 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve ortalamasini aliniz. Ayrica;
* a. standart sapmasini aliniz. 
* b. varyansini aliniz. 
* c. median’ini aliniz. 
* d. en kucuk degeri bulunuz. 
* e. en buyuk degeri bulunuz.

### 27.	Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

### 28.	Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

### 29.	Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

### 30.	10 elemanli random bir vektor olusturun.
* Vektoru seriye cevirip indexleri str olarak belirleyin. 
(ornek: a,b,c,d,e,f,g.. seklinde)
* Index ismine gore serinin 3. elemanina ulasin. 
(ornek: c indexine karsilik gelen deger)
* Serinin index sirasina gore 1. Elamanina ulasin.
* Index ismine gore serinin  2. Ve 7. Elemanlarina ayni anda ulasin. 
(Ornek: b ve g indexine karsilik gelen degerler)
* Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin.
(Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
* Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

### 31.	2 adet 5 elemanli seri olusturun.
* Olusturdugunuz serileri birlestirin.
* Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
* Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

### Master odev ;
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz. 
* Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz. 
(Matris uretme islemini np.random.random((a,b)) fonksiyonu ile yapabilirsiniz. 0-1 arasi istenen boyutlarda array uretir.)