In [1]:
import numpy as np 
import pandas as pd

In [2]:
#1
# A vector is an array with a single dimension 
# (there's no difference between row and column vectors), 
# while a matrix refers to an array with two dimensions.


In [3]:
#2
a=[1,2,3,4,5,6,7,8,9,10]
np.array(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#3
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
#4

np.ones((10,10)) 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
#5
np.full((10,10),9)   #

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [7]:
#6
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [8]:
#7
np.linspace(-1,1,30)   

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [9]:
#8
np.random.randint(0,30,size=(5,6)) 

array([[19, 18, 18, 26, 26, 29],
       [10, 13, 25, 15, 26, 16],
       [15,  4,  3,  3, 25, 29],
       [11, 16,  6, 19, 12, 17],
       [12,  1, 11,  8, 25, 17]])

In [10]:
#9
np.eye(10)  #k=1 ,scalar matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
#10
definition=np.random.randint(0,10,size=(5,10))
print(definition)
print("Number of elements =  ",definition.size)
print("Dimension= ",definition.ndim) 
print("Rows,columns= ",definition.shape)
print("Data Type",definition.dtype)

[[3 1 2 8 1 3 6 1 8 3]
 [1 9 4 5 2 3 4 5 8 9]
 [3 6 3 2 2 1 4 3 9 3]
 [5 3 8 4 5 2 0 7 9 5]
 [6 9 9 4 4 9 7 1 7 9]]
Number of elements =   50
Dimension=  2
Rows,columns=  (5, 10)
Data Type int32


In [12]:
#11
np.random.randint(10, size = (3,4,7))

array([[[2, 6, 8, 0, 4, 1, 3],
        [0, 3, 0, 7, 1, 0, 6],
        [2, 8, 8, 3, 1, 1, 0],
        [7, 9, 4, 4, 8, 2, 8]],

       [[1, 9, 8, 0, 1, 1, 6],
        [7, 5, 6, 5, 1, 9, 8],
        [2, 5, 0, 4, 7, 8, 2],
        [6, 0, 3, 6, 4, 6, 3]],

       [[6, 6, 7, 3, 9, 2, 0],
        [2, 2, 5, 1, 4, 8, 5],
        [5, 1, 5, 0, 0, 5, 8],
        [6, 2, 5, 1, 4, 6, 6]]])

In [13]:
#12
a=np.arange(1,10)
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#13
u=[1,2,3]  
y=[4,5,6]
x=[7,8,9]
t=[0,0,0]

np.concatenate([u,y,x,t]) #lists also can be converted in arrays directly

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0])

In [15]:
#14
e=np.array([[0],
            [1]])
r=np.array([[2,3],
            [4,5]])
np.concatenate([e,r], axis = 1)

array([[0, 2, 3],
       [1, 4, 5]])

In [16]:
#15
# axis=1  -->adds along x-axis   ,horizontally
# axis=0 -->adds along y-axis   ,vertically

In [17]:
#16
t=np.array([0,1])
y=np.array([[2,3],
           [4,5]])
i=np.array([[6],
            [7]])
print(np.vstack([t,y]))
print("-----")
print(np.hstack([y,i]))

[[0 1]
 [2 3]
 [4 5]]
-----
[[2 3 6]
 [4 5 7]]


In [18]:
#17
ex=np.arange(1,11,1)
np.split(ex,[2,4,6])

[array([1, 2]), array([3, 4]), array([5, 6]), array([ 7,  8,  9, 10])]

In [19]:
#18
randex=np.random.randint(0,50,5)
print(np.sort(randex))

randex[-1],randex[3]


[ 2 16 18 28 49]


(2, 16)

In [20]:
#19
r_ex=np.random.randint(20,size=20)
print(r_ex)
r_ex[3],r_ex[5],r_ex[7]


[ 4 19 15 13  0  7  7  4 19 15 19 12 18 14 18 18 10  7 14 19]


(13, 7, 4)

In [21]:
#20
r_ex=np.random.randint(20,size=10)
print(r_ex)
r_ex[4]=2
print(r_ex)


[ 4 19  9  3 14 13  6  2 14 10]
[ 4 19  9  3  2 13  6  2 14 10]


In [22]:
#21
#Diagonal matrix= a square matrix, where all non-diagonal elements are zeros
#Trace matrix=sum of all diagonal elements of the matrix

In [23]:
#22
diag=np.diag([0,1,2,3,4])
diag

for  i in range(5):
    for j in range(5):
        if i==j :
             print(diag[i,j],end=",")



0,1,2,3,4,

In [24]:
#23
g=np.random.randint(10,21,10)
print(g)
g[2:]

[19 19 18 16 12 13 12 18 15 10]


array([18, 16, 12, 13, 12, 18, 15, 10])

In [25]:
h=np.random.randint(0,10,(10,10))
h


array([[6, 7, 9, 1, 7, 5, 7, 2, 4, 6],
       [6, 3, 2, 5, 8, 6, 9, 4, 4, 4],
       [7, 1, 1, 6, 2, 6, 0, 9, 2, 3],
       [1, 8, 4, 5, 5, 2, 1, 7, 5, 2],
       [2, 7, 2, 2, 8, 9, 8, 2, 9, 4],
       [0, 0, 6, 9, 9, 4, 1, 2, 9, 3],
       [1, 0, 0, 0, 4, 1, 3, 3, 4, 8],
       [1, 2, 7, 0, 9, 6, 0, 3, 2, 2],
       [0, 9, 2, 5, 5, 2, 8, 6, 4, 1],
       [1, 3, 8, 4, 9, 5, 8, 6, 2, 5]])

In [26]:
h[2,4]

2

In [27]:
#a
h[:,4]

array([7, 8, 2, 5, 8, 9, 4, 9, 5, 9])

In [28]:
#b
h[1,:]

array([6, 3, 2, 5, 8, 6, 9, 4, 4, 4])

In [29]:
#c
h[2:8,:]

array([[7, 1, 1, 6, 2, 6, 0, 9, 2, 3],
       [1, 8, 4, 5, 5, 2, 1, 7, 5, 2],
       [2, 7, 2, 2, 8, 9, 8, 2, 9, 4],
       [0, 0, 6, 9, 9, 4, 1, 2, 9, 3],
       [1, 0, 0, 0, 4, 1, 3, 3, 4, 8],
       [1, 2, 7, 0, 9, 6, 0, 3, 2, 2]])

In [30]:
#d
h[2:6,3:8]

array([[6, 2, 6, 0, 9],
       [5, 5, 2, 1, 7],
       [2, 8, 9, 8, 2],
       [9, 9, 4, 1, 2]])

In [31]:
#e
h[5:,:5]

array([[0, 0, 6, 9, 9],
       [1, 0, 0, 0, 4],
       [1, 2, 7, 0, 9],
       [0, 9, 2, 5, 5],
       [1, 3, 8, 4, 9]])

In [32]:
#f
h[:,(3,6,9)]

array([[1, 7, 6],
       [5, 9, 4],
       [6, 0, 3],
       [5, 1, 2],
       [2, 8, 4],
       [9, 1, 3],
       [0, 3, 8],
       [0, 0, 2],
       [5, 8, 1],
       [4, 8, 5]])

In [33]:
#g
h[5,5]=2000


In [34]:
#25
j=np.arange(0,50,5)
j

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
#a
j>20


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
#b

j<30

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [37]:
#c
j==33

array([False, False, False, False, False, False, False, False, False,
       False])

In [38]:
#e
j%2


array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [39]:
q26=np.linspace(0,1,50) 
q26

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [40]:
#a
np.std(q26)

0.2945075446869757

In [41]:
#b
np.var(q26)

0.086734693877551

In [42]:
#c
np.median(q26)

0.5

In [43]:
#d
np.min(q26)

0.0

In [44]:
#e
np.max(q26)

1.0

In [45]:
#27
#Pandas Series is much more general and flexible than the one-dimensional NumPy array.
#Pandas series can hold data type as it assigned(int,float,object etc.),
#numpy arrays can hold only one type data at once(all elements must be same type)


In [46]:
#28
seri=pd.Series([0,"hi",1.8,[3,[2,3],"carrot"],True],index=("A","B","C","D","E"))
seri

A                      0
B                     hi
C                    1.8
D    [3, [2, 3], carrot]
E                   True
dtype: object

In [47]:
#29
dic={"France":"Paris","England":"London","Italy":"Rome","Denmark":"Copenhagen","Netherlands":"Amsterdam"}
series_dic=pd.Series(dic)
series_dic


France              Paris
England            London
Italy                Rome
Denmark        Copenhagen
Netherlands     Amsterdam
dtype: object

In [48]:
#30
v=np.random.randint(1,50,10)
v

array([35, 17, 16, 35,  4, 16, 22, 30,  9, 17])

In [49]:
#30-1
f=pd.Series(v,index=("a","b","c","d","e","f","g","h","i","j"))
f


a    35
b    17
c    16
d    35
e     4
f    16
g    22
h    30
i     9
j    17
dtype: int32

In [50]:
#30-2,3
f["c"],f["a"]

(16, 35)

In [51]:
#30-4
f["b"],f["g"]

(17, 22)

In [52]:
#30-5
f["b":"g"]


b    17
c    16
d    35
e     4
f    16
g    22
dtype: int32

In [53]:
f["e":]

e     4
f    16
g    22
h    30
i     9
j    17
dtype: int32

In [54]:
#31
z=pd.Series([{"France":"Paris"},22,"jupyter",4.2,True])
z

0    {'France': 'Paris'}
1                     22
2                jupyter
3                    4.2
4                   True
dtype: object

In [55]:
p=pd.Series([3,"hi",{4:{"England":"London"}},23,1.3])
p

0                             3
1                            hi
2    {4: {'England': 'London'}}
3                            23
4                           1.3
dtype: object

In [56]:
#31-1

uni_s=pd.concat([p,z])
uni_s


0                             3
1                            hi
2    {4: {'England': 'London'}}
3                            23
4                           1.3
0           {'France': 'Paris'}
1                            22
2                       jupyter
3                           4.2
4                          True
dtype: object

In [57]:
#31-2
uni_s.index = np.arange(1, len(uni_s) + 1)
index_uni_s=uni_s
index_uni_s


1                              3
2                             hi
3     {4: {'England': 'London'}}
4                             23
5                            1.3
6            {'France': 'Paris'}
7                             22
8                        jupyter
9                            4.2
10                          True
dtype: object

In [58]:
#31-3
index_uni_s.iloc[[3,4,5]],index_uni_s.loc[[4,5,6]]



(4                     23
 5                    1.3
 6    {'France': 'Paris'}
 dtype: object,
 4                     23
 5                    1.3
 6    {'France': 'Paris'}
 dtype: object)

In [59]:
#MASTER
import numpy as np
import time
counter=0
timer=time.time()
while True:
    counter+=1
    mat_1=np.random.random((6,6))
    mat_2=np.random.random((6,6))
    sub_mat=mat_1-mat_2
    diagonal=np.diag(sub_mat)
    checker=np.all((-0.1<diagonal)&(diagonal< 0.1))
    if checker==True:
        print(f"""
Substraction result
{sub_mat}
Diagonal
{diagonal}""")
        print(f"""
Duration : {time.time()-timer} secs
Turn counter : {counter}  """)
        break


Substraction result
[[ 0.07340931  0.01378633  0.51955392 -0.95056128  0.22811718 -0.03612637]
 [ 0.28628664  0.03894138  0.49624644  0.16404118  0.05571306  0.09889044]
 [ 0.18133441  0.52391004 -0.05325784 -0.01840947 -0.091181   -0.13947664]
 [-0.05909216  0.15230133 -0.04825791  0.07753869  0.07996067 -0.6549745 ]
 [-0.77468859 -0.60860718  0.06076176  0.38067711 -0.0814687  -0.78072158]
 [ 0.57895545  0.40278472  0.8137513   0.31045625 -0.78706301  0.07775661]]
Diagonal
[ 0.07340931  0.03894138 -0.05325784  0.07753869 -0.0814687   0.07775661]

Duration : 2.6371588706970215 secs
Turn counter : 71436  
