In [6]:
import numpy as np

1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

2. 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [7]:
list=np.array(range(10))
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [8]:
i1 = np.zeros((10,10),dtype=int)
i1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [9]:
f1 = np.ones((10,10),dtype=float)
f1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [10]:
i2=np.full((10,10),9,dtype=int)
i2

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [11]:
a2=np.arange(5,25,3)
a2

array([ 5,  8, 11, 14, 17, 20, 23])

7. -1 ile 1 arasinda 30 adet Array olusturunuz.

In [12]:
a3=np.linspace(-1,1,30)
a3

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. 0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [13]:
np.random.randint(0,30,(5,6))

array([[26, 15,  0, 19,  7, 16],
       [ 0,  3, 19, 18,  5,  4],
       [15, 19, 21, 25, 26, 20],
       [ 9,  6, 12,  8,  5,  0],
       [11,  2, 19, 18,  4, 11]])

9. Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

In [14]:
np.eye(10,k=0,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
a. eleman sayisini
b. boyut bilgisini/sayisini
c. satir X sutun bilgisini
d. veri tipini numpy metodlariyla yazdiriniz.

In [15]:
a5=np.random.randint(0,10,(5,10))
a5

array([[8, 0, 7, 3, 1, 9, 3, 6, 1, 9],
       [1, 9, 9, 1, 2, 3, 4, 1, 4, 5],
       [5, 7, 2, 6, 7, 8, 9, 2, 7, 2],
       [7, 8, 4, 4, 1, 4, 3, 0, 3, 1],
       [6, 3, 0, 9, 4, 6, 6, 6, 5, 2]])

In [16]:
a5.ndim

2

In [17]:
a5.shape

(5, 10)

In [18]:
a5.size

50

In [19]:
a5.dtype

dtype('int32')

11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [20]:
a6 = np.random.randint(10, size = (3,4,7))  
a6

array([[[0, 1, 9, 0, 6, 9, 5],
        [3, 9, 3, 9, 3, 7, 0],
        [4, 7, 2, 6, 8, 8, 8],
        [1, 0, 8, 8, 1, 1, 3]],

       [[5, 6, 8, 9, 9, 9, 1],
        [6, 3, 8, 7, 5, 9, 4],
        [4, 7, 7, 7, 7, 5, 2],
        [3, 7, 7, 4, 4, 5, 2]],

       [[1, 9, 5, 6, 0, 0, 7],
        [6, 8, 9, 3, 6, 0, 5],
        [5, 3, 0, 5, 1, 0, 7],
        [3, 6, 9, 0, 2, 1, 4]]])

12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [21]:
a7 = np.arange(1,10)   # tek bouyutlu arrayi, 3 boyutlu matrise cevirdik. 3x3=9 adet eleman olmak zorunda
a7.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [22]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
w = np.array([10, 11, 12])

In [23]:
np.concatenate([x,y,z,w])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [31]:
a7 = np.array([[ 5, 10, 15],[20, 25, 30],[35, 40, 45]])
a8 = np.array([[6,7,8],[8,9,5]])

In [36]:
np.vstack([a7,a8])

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 6,  7,  8],
       [ 8,  9,  5]])

15. Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

axis=0   Satıra göre hesaplanır.
axis=1   Sütun göre hesaplanır. 

16. Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

In [45]:
a9 = np.array([[5,6,5],
            ])

a10 = np.array([[1,2,3], 
            [10,11,12]])


In [46]:
np.vstack([a9,a10])

array([[ 5,  6,  5],
       [ 1,  2,  3],
       [10, 11, 12]])

In [50]:
a11 = np.array([[5,6],
            [6,8]])

a12 = np.array([[1,2,3], 
            [10,11,12]])


In [51]:
np.hstack([a11,a12])

array([[ 5,  6,  1,  2,  3],
       [ 6,  8, 10, 11, 12]])

17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [59]:
a13=np.array(range(0,20,2))
a13

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
np.split(a13, [2,5,8]) 

[array([0, 2]), array([4, 6, 8]), array([10, 12, 14]), array([16, 18])]

18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz. Sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [78]:
a14 = np.random.randint(100, size = (5))  
np.sort(a14)

array([ 9, 12, 15, 39, 73])

In [81]:
a14.sort()
for i in range(5):
    print(f"index {i} = ",a14[i])

index 0 =  9
index 1 =  12
index 2 =  15
index 3 =  39
index 4 =  73


19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [87]:
a15 = np.random.randint(100, size = (20))
a15[3]


14

In [88]:
a15[5]


47

In [89]:
a15[7]

1

20. 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [93]:
a16 = np.random.randint(55, size = (10))
a16

array([36, 34, 11, 18,  9, 38, 38, 38, 35, 47])

In [95]:
a16[4]=100
a16

array([ 36,  34,  11,  18, 100,  38,  38,  38,  35,  47])

21. “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise köşegen matris denir.

Bir kare matriste asal köşegen üzerindeki elemanların toplami


22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [153]:
a18 = np.eye(5,k=0,dtype=int)
a18


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [155]:
a18[0,0]

1

In [156]:
a18[1,1]

1

In [157]:
a18[2,2]

1

In [158]:
a18[3,3]

1

In [159]:
a18[4,4]

1

23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [163]:
a19 = np.random.randint(10,20,(7))
a19

array([12, 15, 17, 15, 12, 17, 14])

In [164]:
a19[3:]

array([15, 12, 17, 14])

24. 10X10 luk bir matris olusturunuz ve 3.satirin 5.sutununa ulasiniz. Ayrica;
a. 5.sutunun tum satirlarina ulasiniz.
b. Tum sutunlarin 2.satirlarina ulasiniz.
c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
e. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
f. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
g. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [166]:
a20 = np.random.randint(10,20,(10,10))
a20

array([[13, 10, 15, 11, 10, 12, 19, 15, 11, 11],
       [19, 19, 12, 18, 12, 14, 11, 14, 17, 15],
       [11, 10, 11, 13, 19, 12, 14, 12, 17, 18],
       [13, 10, 15, 15, 18, 14, 12, 16, 12, 18],
       [10, 15, 15, 15, 17, 12, 12, 16, 13, 19],
       [11, 17, 10, 17, 19, 10, 18, 19, 15, 13],
       [11, 16, 19, 13, 11, 16, 18, 18, 17, 17],
       [12, 12, 11, 17, 17, 14, 17, 11, 18, 16],
       [15, 18, 13, 13, 12, 17, 12, 18, 11, 17],
       [19, 16, 16, 15, 11, 11, 16, 13, 11, 10]])

In [171]:
a20[2,4]

19

In [170]:
a20[:,4]

array([10, 12, 19, 18, 17, 19, 11, 17, 12, 11])

In [174]:
a20[1,:]

array([19, 19, 12, 18, 12, 14, 11, 14, 17, 15])

In [175]:
a20[1:7,:]

array([[19, 19, 12, 18, 12, 14, 11, 14, 17, 15],
       [11, 10, 11, 13, 19, 12, 14, 12, 17, 18],
       [13, 10, 15, 15, 18, 14, 12, 16, 12, 18],
       [10, 15, 15, 15, 17, 12, 12, 16, 13, 19],
       [11, 17, 10, 17, 19, 10, 18, 19, 15, 13],
       [11, 16, 19, 13, 11, 16, 18, 18, 17, 17]])

In [176]:
a20[2:5,3:7]

array([[13, 19, 12, 14],
       [15, 18, 14, 12],
       [15, 17, 12, 12]])

In [177]:
a20[5:,:4]

array([[11, 17, 10, 17],
       [11, 16, 19, 13],
       [12, 12, 11, 17],
       [15, 18, 13, 13],
       [19, 16, 16, 15]])

In [181]:
a20[:,(3,6,9)]

array([[11, 19, 11],
       [18, 11, 15],
       [13, 14, 18],
       [15, 12, 18],
       [15, 12, 19],
       [17, 18, 13],
       [13, 18, 17],
       [17, 17, 16],
       [13, 12, 17],
       [15, 16, 10]])

In [182]:
a20[5,5]=1979
a20

array([[  13,   10,   15,   11,   10,   12,   19,   15,   11,   11],
       [  19,   19,   12,   18,   12,   14,   11,   14,   17,   15],
       [  11,   10,   11,   13,   19,   12,   14,   12,   17,   18],
       [  13,   10,   15,   15,   18,   14,   12,   16,   12,   18],
       [  10,   15,   15,   15,   17,   12,   12,   16,   13,   19],
       [  11,   17,   10,   17,   19, 1979,   18,   19,   15,   13],
       [  11,   16,   19,   13,   11,   16,   18,   18,   17,   17],
       [  12,   12,   11,   17,   17,   14,   17,   11,   18,   16],
       [  15,   18,   13,   13,   12,   17,   12,   18,   11,   17],
       [  19,   16,   16,   15,   11,   11,   16,   13,   11,   10]])

25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz (tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
a. 20 den buyuk olan kac deger var.
b. 30’dan kucuk kac deger var
c. icerisinde 33 gecen kac deger var
d. olusturulan arrayin tum elemanlarini 5 ile carpin.
e. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [183]:
a21=np.arange(0, 50, 5)
a21

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [192]:
x=0
for i in (a21>20):
    if i ==True:
        x+=1
print(x)


5


In [191]:
a21<30
x=0
for i in (a21<30):
    if i ==True:
        x+=1
print(x)

6


In [193]:
x=0
for i in (a21==33):
    if i ==True:
        x+=1
print(x)

0


In [198]:
print(a21*5)


[  0  25  50  75 100 125 150 175 200 225]


In [200]:
print(a21%2)

[0 1 0 1 0 1 0 1 0 1]


26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve ortalamasini aliniz. Ayrica;
a. standart sapmasini aliniz.
b. varyansini aliniz.
c. median’ini aliniz.
d. en kucuk degeri bulunuz.
e. en buyuk degeri bulunuz.

In [205]:
a22= np.linspace(0,1,50)
a22

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [208]:
np.mean(a22)

0.5

In [209]:
np.std(a22) 

0.2945075446869757

In [210]:
np.var(a22)

0.086734693877551

In [211]:
np.median(a22)

0.5

In [212]:
np.min(a22) 

0.0

In [214]:
np.max(a22) 

1.0

27. Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

28. Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

In [219]:
import pandas as pd
seri = pd.Series([1,"aaa",0.9,True], index = ('H','O','S','Q')) 
seri

H       1
O     aaa
S     0.9
Q    True
dtype: object

import pandas as pd

29. Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

In [221]:
dic= {'turkiye':'ankara',
        'france':'paris',
        'italy':'rome',
        'germay':'berlin',
        'japan':'tokyo'}
seri1 = pd.Series(dic)
seri1

turkiye    ankara
france      paris
italy        rome
germay     berlin
japan       tokyo
dtype: object

30. 10 elemanli random bir vektor olusturun.
Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)
Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)
Serinin index sirasina gore 1. Elamanina ulasin.
Index ismine gore serinin 2. Ve 7. Elemanlarina ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)
Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin. (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

In [226]:
a24 = np.random.randint(0,100,(10))
a24

array([45, 55, 37, 46, 50, 10, 97, 63, 10,  3])

In [227]:
seri2 = pd.Series(a24,index=('s','d','q','e','r','t','y','u','m','o'))
seri2

s    45
d    55
q    37
e    46
r    50
t    10
y    97
u    63
m    10
o     3
dtype: int32

In [228]:
seri2['q']

37

In [229]:
seri2[0]

45

In [230]:
seri2[2],seri2[7]

(37, 63)

In [232]:
seri2['d':'y']

d    55
q    37
e    46
r    50
t    10
y    97
dtype: int32

In [233]:
seri2[4:]

r    50
t    10
y    97
u    63
m    10
o     3
dtype: int32

31. 2 adet 5 elemanli seri olusturun.
Olusturdugunuz serileri birlestirin.
Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

In [248]:
seri3 = pd.Series(['a','b','d','g','h'])
seri4 = pd.Series([21,54,8,47,49])
seri5 = pd.concat([seri3,seri4], ignore_index=True)

seri5

0     a
1     b
2     d
3     g
4     h
5    21
6    54
7     8
8    47
9    49
dtype: object

In [251]:
seri5.loc[3:5]

3     g
4     h
5    21
dtype: object

In [253]:
seri5.iloc[3:6]

3     g
4     h
5    21
dtype: object

Master odev ;
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz.

Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz. (Matris uretme islemini np.random.random((a,b)) fonksiyonu ile yapabilirsiniz. 0-1 arasi istenen boyutlarda array uretir.)

In [ ]:

import time
counter=0
time_start=time.time()

while True:

    m1=np.random.random((4,4))
    m2=np.random.random((4,4))
    m=m1-m2
    d=np.diag(m)
    counter+=1
    for i in d:
        if i<1 and i>-1:
            # print(i)
            print(m)
            print(counter)
            time_end=time.time()
            print('time cost',time_end-time_start,'s')
            break
        else:
            continue