In [2]:
import numpy as np 



In [2]:
# vektor tek boyutlu bir dizi matrix 2 boyutlu dizidir.##1

In [4]:
a = np.arange(10)#2
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.zeros((10,10),dtype = 'int')#3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
np.ones((10,10),dtype = 'float')#4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.full((10,10),9,dtype= 'int')#5

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [10]:
np.arange(5,25,3)#6

array([ 5,  8, 11, 14, 17, 20, 23])

In [11]:
np.linspace(-1,1,30)#7

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [12]:
 np.random.randint(0,30,(5,6))#8

array([[14,  1, 13, 14, 10, 24],
       [14, 27, 21, 19,  8, 23],
       [17, 26,  6,  0, 17, 12],
       [16,  3, 14, 24, 25, 18],
       [ 5,  4, 13,  5, 15, 11]])

In [16]:
np.eye(10)#9

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
a =np.random.randint(0,10,(5,10))#10
a

array([[8, 9, 4, 7, 8, 5, 7, 8, 2, 5],
       [3, 2, 4, 5, 4, 3, 3, 9, 4, 5],
       [6, 0, 0, 2, 2, 9, 8, 5, 2, 9],
       [9, 3, 4, 4, 8, 0, 8, 6, 1, 1],
       [3, 4, 6, 8, 6, 3, 7, 8, 9, 5]])

In [23]:
a.ndim




2

In [20]:
a.shape

(5, 10)

In [21]:
a.size

50

In [22]:
a.dtype


dtype('int32')

In [25]:
a = np.random.randint(10, size = (3,4,7))#11
a

array([[[5, 8, 6, 8, 0, 9, 2],
        [8, 5, 4, 3, 4, 9, 2],
        [2, 3, 2, 6, 6, 7, 8],
        [1, 9, 7, 8, 3, 4, 9]],

       [[3, 4, 1, 2, 1, 1, 7],
        [8, 2, 7, 4, 7, 0, 5],
        [5, 2, 4, 3, 7, 4, 0],
        [5, 2, 6, 0, 8, 1, 7]],

       [[9, 9, 2, 4, 9, 2, 9],
        [3, 1, 2, 8, 7, 6, 8],
        [0, 2, 3, 3, 3, 6, 0],
        [8, 5, 5, 5, 5, 4, 6]]])

In [26]:
a=np.arange(1,10)#12
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a.reshape(3,3)#12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
x = np.array([1, 2, 3])#13
y = np.array([4, 5, 6])
z = np.array([7, 9, 11])
a = np.array([12,15,17])

In [30]:
np.concatenate([x,y,z,a])

array([ 1,  2,  3,  4,  5,  6,  7,  9, 11, 12, 15, 17])

In [35]:
a = np.array([[1, 2, 3], #14
              [4, 5, 6]])
y = np.random.randint(0,13,(2,2))

In [36]:
np.concatenate([a,y],axis=1)

array([[1, 2, 3, 7, 0],
       [4, 5, 6, 2, 1]])

In [37]:
# axis = 1 sutun bazli  axis = 0 satir bazli birlestirme yapar##15

In [9]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3, 7, 0])
np.concatenate([x,y],axis = 0)

array([1, 2, 3, 1, 2, 3, 7, 0])

In [18]:
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])


In [19]:
np.vstack([a,b])  #16

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [21]:
a = np.array([[99],
              [99]])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])

In [22]:
np.hstack([a,b])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [24]:
a = np.arange(10)#17
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.split(a, [3,6,9]) 

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([9])]

In [31]:
a = np.random.randint(10, size = 10) #18
a

array([0, 4, 5, 7, 9, 8, 8, 6, 0, 1])

In [32]:
np.sort(a)  

array([0, 0, 1, 4, 5, 6, 7, 8, 8, 9])

In [33]:
a[0]

0

In [35]:
a = np.random.randint(10, size = 20)#19
a

array([8, 2, 1, 7, 8, 6, 1, 9, 9, 1, 8, 5, 1, 6, 6, 6, 0, 0, 2, 5])

In [36]:
a[2],a[4],a[6]

(1, 8, 1)

In [37]:
a = np.random.randint(10, size = 10)#20
a

array([3, 3, 9, 1, 2, 6, 8, 4, 2, 9])

In [38]:
a[3] = 8
a

array([3, 3, 9, 8, 2, 6, 8, 4, 2, 9])

In [39]:
#Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise diagonal matris denir.
#bir kare matriste ilk kosegenlerin toplami trace of a matrixdir.#21

In [41]:
a = np.random.randint(10, size = (5,5))#22
a

array([[3, 0, 5, 0, 3],
       [1, 0, 9, 9, 5],
       [2, 9, 1, 2, 0],
       [0, 9, 1, 8, 8],
       [7, 6, 8, 6, 4]])

In [45]:
a[0,0],a[1,1],a[2,2],a[3,3],a[4,4]

(3, 0, 1, 8, 4)

In [48]:
a = np.arange(10,20)#23
a


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
a[3:]

array([13, 14, 15, 16, 17, 18, 19])

In [50]:
a = np.random.randint(50, size = (10,10))#24
a

array([[38, 48, 29, 40, 42, 24, 14, 49, 28, 23],
       [23, 37, 25, 30, 32, 26, 20, 21, 39, 29],
       [13, 29,  6, 15, 42, 38, 38,  4, 13, 17],
       [11, 47, 17, 30, 19, 18, 22, 26, 49, 46],
       [28, 48, 35,  7, 44, 43, 33, 26, 49, 37],
       [17, 48, 43, 40, 23, 12, 49, 18,  0,  4],
       [38,  2, 12, 17, 38, 10, 42, 11, 44,  8],
       [39,  6, 47,  3, 48, 49, 33,  5,  9, 27],
       [32, 39,  4, 29,  6, 32,  1,  2, 22, 14],
       [ 7, 45, 11,  5,  1, 49, 36, 44, 46, 40]])

In [72]:
a[3,4],  a[4],   a[:,1],   a[:,1:6],   a[2:5,3:7],   a[5:,:4], a[:,[3,6,9]] #a[:,-1:-9:-3]

(19,
 array([28, 48, 35,  7, 44, 43, 33, 26, 49, 37]),
 array([48, 37, 29, 47, 48, 48,  2,  6, 39, 45]),
 array([[  48,   29,   40,   42,   24],
        [  37,   25,   30,   32,   26],
        [  29,    6,   15,   42,   38],
        [  47,   17,   30,   19,   18],
        [  48,   35,    7,   44,   43],
        [  48,   43,   40,   23, 1994],
        [   2,   12,   17,   38,   10],
        [   6,   47,    3,   48,   49],
        [  39,    4,   29,    6,   32],
        [  45,   11,    5,    1,   49]]),
 array([[15, 42, 38, 38],
        [30, 19, 18, 22],
        [ 7, 44, 43, 33]]),
 array([[17, 48, 43, 40],
        [38,  2, 12, 17],
        [39,  6, 47,  3],
        [32, 39,  4, 29],
        [ 7, 45, 11,  5]]),
 array([[40, 14, 23],
        [30, 20, 29],
        [15, 38, 17],
        [30, 22, 46],
        [ 7, 33, 37],
        [40, 49,  4],
        [17, 42,  8],
        [ 3, 33, 27],
        [29,  1, 14],
        [ 5, 36, 40]]))

In [68]:
a[5,5]=1994
a


array([[  38,   48,   29,   40,   42,   24,   14,   49,   28,   23],
       [  23,   37,   25,   30,   32,   26,   20,   21,   39,   29],
       [  13,   29,    6,   15,   42,   38,   38,    4,   13,   17],
       [  11,   47,   17,   30,   19,   18,   22,   26,   49,   46],
       [  28,   48,   35,    7,   44,   43,   33,   26,   49,   37],
       [  17,   48,   43,   40,   23, 1994,   49,   18,    0,    4],
       [  38,    2,   12,   17,   38,   10,   42,   11,   44,    8],
       [  39,    6,   47,    3,   48,   49,   33,    5,    9,   27],
       [  32,   39,    4,   29,    6,   32,    1,    2,   22,   14],
       [   7,   45,   11,    5,    1,   49,   36,   44,   46,   40]])

In [70]:
b = np.arange(0,50,5)#25
b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [78]:
np.sum(b > 20) 

5

In [79]:
np.sum(b > 30) 

3

b==33

In [80]:
np.sum(b==33) 

0

In [77]:
(2 * b)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
b%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [86]:
a =np.random.normal(0,1,size = 50)#26
a

array([ 0.38558656, -1.09344483, -0.75672566,  0.80883721, -1.84416694,
        1.91052919, -1.29767976,  0.52225535, -0.09411771,  0.86943912,
       -0.4285428 , -0.22888421,  0.99345517,  0.78805059, -0.18687062,
        1.10491104,  1.02966122,  0.97916518, -0.27752075, -1.80702533,
       -0.10022159, -0.51552734, -0.99254654,  1.42000693, -0.49261999,
       -2.44696745, -1.61261107,  0.76286396,  0.45732944, -1.19145782,
       -0.33962827, -0.51729676,  0.11383915,  0.5324043 , -0.85994909,
        0.69581445,  0.34887221,  0.56281952, -0.88067212, -1.50337591,
       -0.24619257, -0.74827542, -0.55369555,  0.48195798, -0.8078467 ,
        0.52669663,  1.35085442,  0.36208008,  1.58399188,  0.27388093])

In [87]:
np.mean(a) 

-0.0591712061495891

In [88]:
np.std(a) 

0.9690743162627258

In [89]:
np.var(a)

0.9391050304400695

In [90]:
np.median(a)

-0.09716965098875119

In [91]:
np.min(a)

-2.4469674481829853

In [92]:
np.max(a)

1.9105291853171178

In [93]:
#27#Pandalar daha fazla bellek tüketir. Numpy bellek açısından verimlidir.
#Panda serisinin indekslenmesi, numpy dizilerine kıyasla çok yavaştır. Numpy Dizilerinin indekslenmesi çok hızlıdır.

In [5]:
import pandas as pd

In [106]:
seri = pd.Series(["Ahmet","Mehmet",3, 4.6, None, " "],index = ('A','B','C','D','E','F'))#28
seri

A     Ahmet
B    Mehmet
C         3
D       4.6
E      None
F          
dtype: object

In [107]:
sozluk = { 'fransa' : 'paris', 'turkiye' :'istanbul', 'amerika' : 'washington d.c.','iran':'tahran','irak':'bagdat'}#29

In [109]:
ulke = pd.Series(sozluk)
ulke

fransa               paris
turkiye           istanbul
amerika    washington d.c.
iran                tahran
irak                bagdat
dtype: object

In [110]:
a = np.random.randint(10,size =10)
a

array([4, 8, 4, 2, 9, 1, 6, 9, 7, 9])

In [117]:
seri3 = pd.Series((a),index = ('a','b','c','d','e','f','g','h','i','j'))#30
seri3

a    4
b    8
c    4
d    2
e    9
f    1
g    6
h    9
i    7
j    9
dtype: int32

In [119]:
seri3['c']

4

In [120]:
seri3[1]

8

In [121]:
seri3[["b","g"]] 

b    8
g    6
dtype: int32

In [125]:
seri3["b":"g"] 

b    8
c    4
d    2
e    9
f    1
g    6
dtype: int32

In [126]:
seri3[4:]

e    9
f    1
g    6
h    9
i    7
j    9
dtype: int32

In [6]:
a = pd.Series([1,2,3,4,5]) #31
b = pd.Series(['a','b','c','d','e'])
seri = pd.concat([a,b])
seri

0    1
1    2
2    3
3    4
4    5
0    a
1    b
2    c
3    d
4    e
dtype: object

In [7]:
seri=pd.Series([1,2,3,4,5,'a','b','c','d','e'],index = (1,2,3,4,5,6,7,8,9,10))
seri

1     1
2     2
3     3
4     4
5     5
6     a
7     b
8     c
9     d
10    e
dtype: object

In [11]:
seri.loc[5],seri.loc[6],seri.loc[7]

(5, 'a', 'b')

In [12]:
seri.iloc[4],seri.iloc[5],seri.iloc[6]

(5, 'a', 'b')

In [3]:
import time # master
start_time = time.time()
count = 0
while True:
    count += 1
    first = np.random.rand(10,10)
    second = np.random.rand(10,10)
    fark = first - second
    diagonal = np.diag(fark)
    if len(list(filter(lambda x : x>-0.1 and x<0.1,diagonal))) == 10:
        break
print(diagonal)
print(time.time() - start_time)
print(count)

       

[ 0.07147746  0.05807539 -0.09542339  0.00301053 -0.0129048  -0.0110864
  0.04789441 -0.02194366 -0.09590269 -0.05185034]
402.3587725162506
28024096
