### 1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

vector is one dimestion wheras matris is two.

### 2. 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [3]:
import numpy as np 
a = [1,2,3,4,5,6,7,8,9,10]
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [3]:
np.zeros((10,10), dtype = 'int32') 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.


In [5]:
np.ones((10,10), dtype = 'float32') 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

### 5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [6]:
np.full((10,10),9)  

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

### 6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.


In [7]:
np.arange(5,25,3)    

array([ 5,  8, 11, 14, 17, 20, 23])

### 7. -1 ile 1 arasinda 30 adet Array olusturunuz.


In [9]:
np.linspace(-1,1,30)  

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

### 8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [10]:
np.random.randint(0,30, (5,6))   

array([[16, 20, 10,  1, 24, 16],
       [ 3,  7, 24,  4, 20,  8],
       [12, 25, 19, 12,  5, 10],
       [28,  7,  6, 16, 23,  1],
       [22, 22, 29, 17,  2,  3]])

### 9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz

In [11]:
np.eye(10)     

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### 10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
* a. eleman sayisini 
* b. boyut bilgisini/sayisini 
* c. satir X sutun bilgisini 
* d. veri tipini numpy metodlariyla yazdiriniz.


In [15]:
a=np.random.randint(0,10, (5,10))  
a

array([[5, 3, 1, 8, 6, 0, 6, 0, 1, 8],
       [4, 0, 0, 5, 4, 4, 4, 1, 3, 7],
       [2, 0, 7, 8, 3, 0, 9, 3, 5, 3],
       [8, 4, 6, 3, 5, 9, 9, 2, 9, 2],
       [4, 5, 1, 9, 1, 8, 8, 4, 8, 3]])

In [20]:
print("Toplam eleman sayisi =  ",a.size)
print("Boyut sayisi =  ",a.ndim) 
print("satir, sutun bilgisi =  ",a.shape)
print("Veri tipi =  ",a.dtype)

Toplam eleman sayisi =   50
Boyut sayisi =   2
satir, sutun bilgisi =   (5, 10)
Veri tipi =   int32


### 11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [24]:
a = np.random.randint(10, size = (3,4,7))
a

array([[[3, 3, 1, 9, 3, 2, 2],
        [9, 2, 7, 1, 2, 6, 9],
        [6, 6, 2, 3, 2, 5, 3],
        [5, 2, 3, 3, 0, 2, 7]],

       [[2, 8, 0, 3, 6, 2, 3],
        [6, 1, 9, 1, 6, 7, 3],
        [8, 8, 2, 9, 7, 7, 7],
        [2, 9, 4, 5, 0, 3, 7]],

       [[8, 1, 1, 0, 5, 8, 1],
        [1, 4, 4, 8, 9, 0, 6],
        [1, 4, 8, 7, 3, 7, 0],
        [0, 2, 7, 1, 0, 5, 8]]])

### 12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [27]:
np.arange(1,10)
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [5]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([4, 5, 6, 7, 8])
z = np.array([3, 4, 6, 8, 4])
q = np.array([8, 5, 4, 3, 2])
np.concatenate([x,y,z,q])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8, 3, 4, 6, 8, 4, 8, 5, 4, 3, 2])

### 14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [6]:
a = np.array([[11],
              [22]])

b = np.array([[4, 5, 6], 
              [8, 4, 5]])
np.hstack([a,b])

array([[11,  4,  5,  6],
       [22,  8,  4,  5]])

### 15. Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

In [8]:
# axis 1=     birlestirme islemini yatay (sutun) olarak yapar  1 sutun, 0satir
# axis 0=     birlestirme islemini dikey (satir) olarak yapar  0 sutun, 1satir

### 16. Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.


In [7]:
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])
np.vstack([a,b])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

### 17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz

In [28]:
x = np.random.randint(43, size =10) 
x
np.split(x, [2,5,7]) 

[array([30,  1]), array([29,  6,  3]), array([20, 12]), array([10, 35,  6])]

### 18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz. Sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.


In [4]:
x = np.random.randint(99, size =11) 
x




array([73, 56, 45, 73, 76, 65,  3, 66,  7, 46, 43])

In [11]:
np.sort(x)
x[4]



76

### 19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [17]:
a = np.random.randint(55, size = 20)
a[3]
a[5]
a[7]

18

### 20. 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.


In [20]:
a = np.random.randint(88, size = 10)
a

array([58, 82,  2,  2, 10, 31, 40, 30,  5, 41])

In [22]:
a[4]=55
a

array([58, 82,  2,  2, 55, 31, 40, 30,  5, 41])

21. “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.


### 22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [24]:
a = np.random.randint(88, size =(5,5))
a

array([[13, 85, 53, 22, 85],
       [34, 36, 42, 15, 35],
       [24, 60, 36, 50, 31],
       [24, 51, 80,  6,  4],
       [39,  0, 71, 51,  4]])

In [26]:
a[0,0]
a[1,1]
a[2,2]
a[3,3]
a[4,4]






4

### 23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [36]:
a = np.random.randint(10,20, size =10)
a[3:]


array([16, 17, 13, 17, 10, 15, 18])


### 24. 10X10 luk bir matris olusturunuz ve 3.satirin 5.sutununa ulasiniz. Ayrica;
* a. 5.sutunun tum satirlarina ulasiniz. 
* b. Tum sutunlarin 2.satirlarina ulasiniz. 
* c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
* d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
* e. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
* f. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
* g. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [38]:
a = np.random.randint(33, size =(10,10))
a

array([[29, 12,  5, 24,  5,  1,  7,  0,  6,  1],
       [ 7, 13,  2, 16, 26, 32,  8, 20, 11,  2],
       [32,  2, 11,  2, 17, 20, 22,  1,  4,  0],
       [22, 28, 17, 22,  4, 30, 24,  1, 11,  8],
       [25, 24, 19, 27, 12,  0,  6, 32,  4,  6],
       [ 5, 27, 12, 24, 15, 28, 13, 28, 32, 27],
       [ 5, 25, 28, 12, 27, 22, 17,  3, 12,  6],
       [12, 17,  6,  3, 13, 18, 15, 18, 27, 27],
       [11, 10,  0, 11, 28,  0,  0,  9, 12, 30],
       [13,  2,  2, 26,  6, 28, 28,  3, 31, 31]])

In [52]:
# a[:,5]
# a[2,:]
# a[2:7,:]
# a[2:5,3:7]
# a[5:,:4]
# a[:,3::3]
a[5,5]=1992
a


array([[  29,   12,    5,   24,    5,    1,    7,    0,    6,    1],
       [   7,   13,    2,   16,   26,   32,    8,   20,   11,    2],
       [  32,    2,   11,    2,   17,   20,   22,    1,    4,    0],
       [  22,   28,   17,   22,    4,   30,   24,    1,   11,    8],
       [  25,   24,   19,   27,   12,    0,    6,   32,    4,    6],
       [   5,   27,   12,   24,   15, 1992,   13,   28,   32,   27],
       [   5,   25,   28,   12,   27,   22,   17,    3,   12,    6],
       [  12,   17,    6,    3,   13,   18,   15,   18,   27,   27],
       [  11,   10,    0,   11,   28,    0,    0,    9,   12,   30],
       [  13,    2,    2,   26,    6,   28,   28,    3,   31,   31]])

### 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz (tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

* a. 20 den buyuk olan kac deger var. 
* b. 30’dan kucuk kac deger var 
* c. icerisinde 33 gecen kac deger var 
* d. olusturulan arrayin tum elemanlarini 5 ile carpin. 
* e. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [60]:
d=np.arange(0,50,5)   
np.sum(d>20)
np.sum(d<30)
d*5
d%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

### 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve ortalamasini aliniz. Ayrica;
* a. standart sapmasini aliniz. 
* b. varyansini aliniz. 
* c. median’ini aliniz. 
* d. en kucuk degeri bulunuz. 
* e. en buyuk degeri bulunuz.

In [88]:
a = np.random.random_sample(50)
a

array([0.90154977, 0.52995788, 0.30773557, 0.76920689, 0.48157847,
       0.37241469, 0.14085713, 0.4922011 , 0.57804041, 0.09688548,
       0.20465698, 0.95898826, 0.25476577, 0.45917048, 0.00721687,
       0.63390935, 0.15646243, 0.46233903, 0.4327995 , 0.0362047 ,
       0.5001654 , 0.82347806, 0.73288399, 0.24591448, 0.81728161,
       0.59397829, 0.77799908, 0.84131385, 0.05249806, 0.76833114,
       0.50199076, 0.05846487, 0.91814285, 0.84133627, 0.7525665 ,
       0.09183082, 0.51867418, 0.68811295, 0.03416036, 0.47300299,
       0.973221  , 0.0814551 , 0.0676852 , 0.81789372, 0.6886003 ,
       0.26553768, 0.52215519, 0.63290437, 0.14095834, 0.7155101 ])

In [74]:
np.mean(a)
np.std(a)
np.var(a) 
np.median(a)
np.min(a)
np.max(a)

-0.37758806804847755

### 27.	Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

The powerful tools of pandas are Data frame and Series;Whereas the powerful tool of numpy is Arrays-
Pandas has index-
Pandas has a better performance when number of rows is 500K or more;Numpy has a better performance when number of rows is 50K or less-
Pandas offers 2d table object called DataFrame;Numpy is capable of providing multi-dimensional arrays.



### 28.	Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

In [1]:
import pandas as pd
seri = pd.Series([62,5,44,24], index = ('A','B','C','D'))
seri


A    62
B     5
C    44
D    24
dtype: int64

### 29.	Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)


In [3]:
dict = {'Fransa':'Paris','Türkiye':'Ankara','italya':'Roma','Amerika':'Washington','Yunanistan':'Atina'}
seri = pd.Series(dict)
seri

Fransa             Paris
Türkiye           Ankara
italya              Roma
Amerika       Washington
Yunanistan         Atina
dtype: object

### 30.	10 elemanli random bir vektor olusturun.
* Vektoru seriye cevirip indexleri str olarak belirleyin. 
(ornek: a,b,c,d,e,f,g.. seklinde)
* Index ismine gore serinin 3. elemanina ulasin. 
(ornek: c indexine karsilik gelen deger)
* Serinin index sirasina gore 1. Elamanina ulasin.
* Index ismine gore serinin  2. Ve 7. Elemanlarina ayni anda ulasin. 
(Ornek: b ve g indexine karsilik gelen degerler)
* Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin.
(Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
* Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

In [2]:
import numpy as np
import pandas as pd
v=np.random.randint(20, size =10)
seri=pd.Series(v, index=('a','b','c','d','e','f','g','h','i','t'))
seri

a    19
b    13
c     2
d    15
e    10
f     4
g     5
h     3
i     2
t    18
dtype: int32

In [6]:
# seri[2]
# seri[0]
# seri[0]
# [seri['b'],seri['g']]
# seri[1:7]
seri[4:]

e    15
f    18
g    17
h    17
i     9
t     8
dtype: int32

### 31.	2 adet 5 elemanli seri olusturun.
* Olusturdugunuz serileri birlestirin.
* Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
* Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

In [6]:
x=np.random.randint(0, 9, 5)
y=np.random.randint(0, 9, 5)
x
y

array([7, 7, 2, 1, 5])

In [11]:
x=pd.Series(x)
y=pd.Series(y)
seri=pd.concat([x, y], axis=0).reset_index()
seri


index  0
0      0  8
1      1  0
2      2  2
3      3  8
4      4  3
5      0  7
6      1  7
7      2  2
8      3  1
9      4  5

In [12]:
seri.loc[4:6]

index  0
4      4  3
5      0  7
6      1  7

In [14]:
seri.iloc[4:7]

index  0
4      4  3
5      0  7
6      1  7

### Master odev ;
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz. 
* Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz. 
(Matris uretme islemini np.random.random((a,b)) fonksiyonu ile yapabilirsiniz. 0-1 arasi istenen boyutlarda array uretir.)

In [63]:
import time
t = time.time()
count = 0
while True:
    count += 1
    first = np.random.rand(5,5)
    second = np.random.rand(5,5)
    fark = first - second
    diagonal = np.diag(fark)
    if len(list(filter(lambda x : x>-0.1 and x<0.1,diagonal))) == 5:
        break
print(diagonal)
print(time.time()-t)
print(count)


[-0.09019989  0.06707718 -0.00779511 -0.01605411  0.03320188]
0.06482625007629395
2383
