In [1]:
import numpy as np

Q1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

A1. Vektörler tek boyutludur . Tek array barındırır. Matrisler ise çok boyutlu ve birden fazla array barındırırlar


10 elemanli bir listeden NumPy Array’i olusturunuz.

In [2]:
liste = range(1,10)
array = np.array(liste)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [3]:
array = np.zeros(100).reshape(10,10)
array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [4]:
array = np.ones(100,float).reshape(10,10)
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [5]:
array = np.random.randint(9,10,size = (10,10))
array

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [6]:
array = np.arange(5,25,3)
array

array([ 5,  8, 11, 14, 17, 20, 23])

-1 ile 1 arasinda 30 adet Array olusturunuz.

In [7]:
array = np.random.randn(30)
array

array([-1.49671316, -0.30259712,  0.35202113,  0.79349213, -0.65056532,
        2.02500156,  2.64203092, -1.7119453 ,  1.87311196, -1.27397394,
        0.36098585,  0.80277089, -1.52324766,  1.92589095,  1.78651353,
        1.13884378, -0.01413956, -1.16627802, -0.76242731,  1.53021948,
        0.96685344,  0.8437062 , -0.4174072 ,  1.15109502, -0.0898263 ,
        0.23836333, -3.47800263, -1.63244156, -0.3903193 , -0.47936473])

0 ile 30 arasinda 5x6’lik bir matris olusturun

In [8]:
array = np.random.randint(0,30,size=(5,6))
array

array([[15, 16, 17, 22,  2, 23],
       [26,  2, 22,  5, 25,  1],
       [18, 24,  7,  7, 21,  7],
       [ 6, 23, 13,  4, 14, 19],
       [ 2,  3,  3,  7, 11,  7]])

Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

In [10]:
array = np.eye(10)
array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;

a. eleman sayisini
b. boyut bilgisini/sayisini
c. satir X sutun bilgisini
d. veri tipini numpy metodlariyla yazdiriniz.

In [11]:
array = np.random.randint(1,11,size=(5,10))
array.size
array.ndim
array.shape
array.dtype

dtype('int64')

0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [ ]:
array = (np.random.randint(10,size=(3,4,7)))
array

Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [ ]:
vektor = np.random.randint(1,25,9)
vektor.reshape(3,3)

4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [ ]:
vektor1 = np.random.randint(1,15,5)
vektor2 = np.random.randint(1,15,5)
vektor3 = np.random.randint(1,15,5)
vektor4 = np.random.randint(1,15,5)
vektor1+vektor2+vektor3+vektor4

2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz

In [ ]:
vektor1 = np.random.randint(1,15,4).reshape(2,2)
vektor2 = np.random.randint(1,15,4).reshape(2,2)
np.hstack([vektor1,vektor2])

Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

Axis 1 kolonlardır 0 ise satır bazlı işlem yaptırır.

Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

In [ ]:
vektor1 = np.random.randint(1,15,4).reshape(2,2)
vektor2 = np.random.randint(1,15,6).reshape(3,2)
print(vektor1)
print(vektor2)

10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [ ]:
array = np.arange(1,11)
np.split(array,[1,2,3])

Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz. Sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [ ]:
array = np.random.randint(1,20,10)
array.sort()
print(array.argsort(),array)

20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [ ]:
array = np.random.randint(500,size=(20))
print(array[3])
print(array[5])
print(array[7])

10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [ ]:
print(array[4])
array[4]= 100
print(array[4])

“Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

* dioganal = 'köşegenler hariç her yer 0 olan matrixler.
* trace matrix = sol üst köşegenden sağ alt köşegene uzanan sayıların toplamıdır.

5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [ ]:
array = np.arange(1,26).reshape(5,5)
print(array)
diagonal = np.diag(np.diag(array))
diagonal

0 ile 1 arasinda 50 elamanli bir array olusturunuz ve ortalamasini aliniz. Ayrica;

a. standart sapmasini aliniz.
b. varyansini aliniz.
c. median’ini aliniz.
d. en kucuk degeri bulunuz.
e. en buyuk degeri bulunuz.

In [ ]:
print(array)
print(array.mean())
print(np.var(array))
print(np.median(array))
print(np.min(array))
print(np.max(array))

Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

Birinde index vardır birinde yoktur.

In [ ]:
import pandas as pd

Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli
bir seri olusturunuz

In [ ]:
seri = pd.Series([1,2,3,4,5],['A','B','C','D','E'])\n",
seri

Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

In [ ]:
sozluk = {'Türkiye':'Ankara','Hollanda':'Amsterdam','Amerika':'Washington','Fransa':'Paris','Almanya':'Berlin'}
seri = pd.Series(sozluk)
seri

10 elemanli random bir vektor olusturun.

Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)
Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)
Serinin index sirasina gore 1. Elamanina ulasin.
Index ismine gore serinin 2. Ve 7. Elemanlarina ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)
Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin. (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

In [ ]:
vektor = np.array(['a','b','c','d','e','f','g','h','i','m'])
seri = pd.Series(range(1,11),index=(vektor),dtype=str)
seri