In [2]:
# Q1=A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions.

In [3]:
# Q2
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Q3
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
# Q4
np.ones((10,10),dtype=float)



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
# Q5
np.full((10,10),9) 

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [12]:
# Q6
b = np.arange(5,25,3)
b

array([ 5,  8, 11, 14, 17, 20, 23])

In [7]:
# Q7
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [9]:
# Q8
np.random.randint(0,30, (5,6)) 

array([[27,  6, 12, 10, 22, 24],
       [24, 12, 12,  0, 27, 14],
       [28, 18, 21, 21,  4,  3],
       [ 2,  3, 20, 22, 25,  6],
       [ 6,  0, 13, 25, 27, 13]])

In [8]:
# Q9
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
# 10
x=np.random.randint(0,10, (5,10))
x


array([[1, 1, 0, 2, 4, 4, 6, 3, 7, 9],
       [3, 0, 6, 3, 6, 5, 2, 3, 0, 0],
       [5, 3, 6, 2, 5, 0, 6, 1, 7, 5],
       [0, 1, 6, 2, 2, 8, 6, 0, 4, 8],
       [1, 2, 7, 9, 0, 0, 2, 9, 2, 4]])

In [12]:
print("Boyut sayisi =  ",x.ndim) 
print("satir, sutun bilgisi =  ",x.shape)  #BOYUT BILGISI ? 
print("Toplam eleman sayisi =  ",x.size)
print("Veri tipi =  ",x.dtype)

Boyut sayisi =   2
satir, sutun bilgisi =   (5, 10)
Toplam eleman sayisi =   50
Veri tipi =   int32


In [13]:
# Q11
a = np.random.randint(10, size = (3,4,7))
a


array([[[5, 4, 2, 3, 1, 9, 3],
        [7, 5, 6, 1, 7, 1, 3],
        [7, 0, 6, 5, 7, 4, 7],
        [0, 0, 6, 8, 0, 7, 9]],

       [[5, 5, 9, 0, 9, 2, 7],
        [1, 1, 7, 2, 8, 0, 7],
        [9, 4, 2, 8, 8, 9, 4],
        [9, 3, 4, 3, 7, 1, 6]],

       [[9, 7, 9, 3, 7, 2, 3],
        [6, 3, 3, 5, 9, 9, 7],
        [1, 9, 0, 0, 9, 8, 8],
        [8, 2, 0, 9, 9, 5, 5]]])

In [18]:
# Q12

np.arange(6,15)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(6,15).reshape(3,3)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
# Q13
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
t = np.array([10, 11, 12])



In [22]:
np.concatenate([x,y,z,t])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
# Q14
a = np.array([[9, 8, 7], 
              [6, 5, 4]])
b=np.random.randint(0,10, (2,2))



In [24]:
np.hstack([a,b])

array([[9, 8, 7, 5, 6],
       [6, 5, 4, 3, 9]])

In [ ]:
# Q15
Axis 0 is the first dimension (the rows), and axis 1 is the second dimension (the columns). 

In [25]:
# Q16
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4],
             [12,11,10]])
np.vstack([a,b]) 

array([[ 1,  2,  3],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [12, 11, 10]])

In [28]:
a = np.array([[1],
              [2]])

b = np.array([[4, 5, 6], 
              [7, 8, 9]])
np.hstack([a,b])


array([[1, 4, 5, 6],
       [2, 7, 8, 9]])

In [29]:
#Q17
x = [10, 20, 30, 99, 99, 33, 22, 11,333,444]
x

[10, 20, 30, 99, 99, 33, 22, 11, 333, 444]

In [30]:
np.split(x, [2,5,8])  


[array([10, 20]), array([30, 99, 99]), array([33, 22, 11]), array([333, 444])]

In [32]:
# Q18
a = np.random.randint(10, size = 15)
a

array([8, 7, 4, 6, 0, 9, 2, 7, 7, 6, 8, 4, 5, 3, 6])

In [34]:
-np.sort(-a)

array([9, 8, 8, 7, 7, 7, 6, 6, 6, 5, 4, 4, 3, 2, 0])

In [38]:
a[0]

8

In [39]:
a[-2]

3

In [40]:
# Q19
b = np.random.randint(15, size = 20)
b

array([10, 14,  4,  7,  6, 11,  7, 14, 11,  0,  1,  8,  6,  7,  5, 14,  1,
       13, 13, 13])

In [42]:
b[2]


4

In [43]:
b[4]


6

In [44]:
b[6]

7

In [49]:
# Q20
c = np.random.randint(10, size = 10)
c

array([5, 4, 4, 8, 9, 1, 6, 5, 9, 8])

In [50]:
c[2]=3
c

array([5, 4, 3, 8, 9, 1, 6, 5, 9, 8])

In [ ]:
# Q21
# Diagonal matris: A diagonal matrix is a matrix in which the entries outside the main diagonal are all zero.
# Trace Matris: The trace of a matrix is the sum of the diagonal elements of the matrix



In [56]:
# 22
x = np.diag([10, 20, 30, 40, 50])
x

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 50]])

In [57]:
x[0,0],x[1,1],x[2,2],x[3,3],x[4,4]

(10, 20, 30, 40, 50)

In [59]:
# 23
a=np.random.randint(10,20,(10))
a


array([13, 14, 18, 11, 13, 17, 11, 19, 18, 12])

In [60]:
a[3:]

array([11, 13, 17, 11, 19, 18, 12])

In [61]:
# 24
x=np.random.randint(0,10, (10,10))
x

array([[0, 6, 8, 0, 4, 2, 4, 4, 7, 8],
       [3, 5, 2, 7, 9, 0, 2, 2, 7, 7],
       [7, 2, 9, 0, 6, 7, 2, 6, 9, 1],
       [7, 3, 3, 6, 8, 6, 9, 1, 5, 1],
       [7, 0, 7, 4, 8, 7, 1, 1, 3, 9],
       [9, 1, 9, 0, 7, 8, 3, 7, 9, 2],
       [9, 0, 6, 0, 5, 5, 0, 6, 3, 7],
       [8, 4, 9, 8, 8, 3, 9, 7, 7, 7],
       [6, 7, 4, 0, 3, 3, 5, 4, 7, 8],
       [8, 2, 5, 7, 2, 4, 8, 5, 6, 4]])

In [63]:
x[2,4]

6

In [65]:
#a 
x[:4]

array([[0, 6, 8, 0, 4, 2, 4, 4, 7, 8],
       [3, 5, 2, 7, 9, 0, 2, 2, 7, 7],
       [7, 2, 9, 0, 6, 7, 2, 6, 9, 1],
       [7, 3, 3, 6, 8, 6, 9, 1, 5, 1]])

In [66]:
# b
x[1,:]


array([3, 5, 2, 7, 9, 0, 2, 2, 7, 7])

In [70]:
# c
x[1:6:]

array([[3, 5, 2, 7, 9, 0, 2, 2, 7, 7],
       [7, 2, 9, 0, 6, 7, 2, 6, 9, 1],
       [7, 3, 3, 6, 8, 6, 9, 1, 5, 1],
       [7, 0, 7, 4, 8, 7, 1, 1, 3, 9],
       [9, 1, 9, 0, 7, 8, 3, 7, 9, 2]])

In [71]:
#d
x[2:5,3:7]

array([[0, 6, 7, 2],
       [6, 8, 6, 9],
       [4, 8, 7, 1]])

In [72]:
# e
x[5:,:4]

array([[9, 1, 9, 0],
       [9, 0, 6, 0],
       [8, 4, 9, 8],
       [6, 7, 4, 0],
       [8, 2, 5, 7]])

In [73]:
# f
x[:,(3,6,9)]

array([[0, 4, 8],
       [7, 2, 7],
       [0, 2, 1],
       [6, 9, 1],
       [4, 1, 9],
       [0, 3, 2],
       [0, 0, 7],
       [8, 9, 7],
       [0, 5, 8],
       [7, 8, 4]])

In [78]:
x[5,5] = 1992
x

array([[   0,    6,    8,    0,    4,    2,    4,    4,    7,    8],
       [   3,    5,    2,    7,    9,    0,    2,    2,    7,    7],
       [   7,    2,    9,    0,    6,    7,    2,    6,    9,    1],
       [   7,    3,    3,    6,    8,    6,    9,    1,    5,    1],
       [   7,    0,    7,    4,    8,    7,    1,    1,    3,    9],
       [   9,    1,    9,    0,    7, 1992,    3,    7,    9,    2],
       [   9,    0,    6,    0,    5,    5,    0,    6,    3,    7],
       [   8,    4,    9,    8,    8,    3,    9,    7,    7,    7],
       [   6,    7,    4,    0,    3,    3,    5,    4,    7,    8],
       [   8,    2,    5,    7,    2,    4,    8,    5,    6,    4]])

In [79]:
# Q25
a= np.arange(0, 50, 5)
a


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [80]:
#a
a>20

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
#b
a<30

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [82]:
#c
a==33

array([False, False, False, False, False, False, False, False, False,
       False])

In [83]:
#d
a*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [84]:
#e
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [88]:
#Q26
x=np.random.randint(0,10,50)
x

array([4, 1, 6, 9, 4, 9, 4, 4, 3, 3, 6, 1, 7, 6, 1, 4, 6, 0, 2, 4, 1, 8,
       5, 3, 6, 0, 9, 7, 9, 2, 2, 8, 6, 4, 9, 3, 3, 3, 7, 7, 5, 5, 1, 5,
       7, 2, 3, 4, 6, 6])

In [89]:
np.mean(x)

4.6

In [90]:
#a
np.std(x)

2.5298221281347035

In [91]:
#b
np.var(x)

6.4

In [92]:
#c
np.median(x)

4.0

In [93]:
#d
np.min(x)

0

In [94]:
#e
np.max(x)

9

In [ ]:
#Q27
# When we have to work on Tabular data, we prefer the pandas module. When we have to work on Numerical data, we prefer the numpy module.
# The powerful tools of pandas are Data frame and Series. Whereas the powerful tool of numpy is Arrays.
# Pandas consume more memory. Numpy is memory efficient.
# Pandas has a better performance when number of rows is 500K or more.Numpy has a better performance when number of rows is 50K or less.
# Indexing of the pandas series is very slow as compared to numpy arrays.Indexing of numpy Arrays is very fast.
# Pandas offers 2d table object called DataFrame. Numpy is capable of providing multi-dimensional arrays.

In [100]:
#Q28
import pandas as pd


In [105]:
seri1 = pd.Series(["Ahmet","Mehmet",3, 4.6, None, " "], index = ('A','B','C','D','E','F'))
seri1


A     Ahmet
B    Mehmet
C         3
D       4.6
E      None
F          
dtype: object

In [107]:
#29
sozluk = { "Turkey" :"Ankara", "Netherlands" : "Amsterdam", "Germany" : "Berlin", "Japan": "Tokyo","Greece": "Athens"}
sozluk

{'Turkey': 'Ankara',
 'Netherlands': 'Amsterdam',
 'Germany': 'Berlin',
 'Japan': 'Tokyo',
 'Greece': 'Athens'}

In [108]:
seri2 = pd.Series(sozluk)
seri2

Turkey            Ankara
Netherlands    Amsterdam
Germany           Berlin
Japan              Tokyo
Greece            Athens
dtype: object

In [114]:
#30
npa=np.random.randint(1,10,(10))
npa

array([2, 2, 4, 6, 3, 7, 5, 8, 1, 6])

In [115]:
seri3=pd.Series(npa,index = ('a','b','c','d','e','f','g','h','ı','i'))
seri3

a    2
b    2
c    4
d    6
e    3
f    7
g    5
h    8
ı    1
i    6
dtype: int32

In [116]:
seri3["c"]

4

In [118]:
seri3[1]

2

In [119]:
seri3[[2,7]]

c    4
h    8
dtype: int32

In [122]:
seri3[2:7]

c    4
d    6
e    3
f    7
g    5
dtype: int32

In [123]:
seri3[4:]

e    3
f    7
g    5
h    8
ı    1
i    6
dtype: int32

In [127]:
#Q31
seri1 = pd.Series([1,2,3,4,5]) 
seri2 = pd.Series([6,7,8,9,10]) 


In [131]:
seri = pd.concat([seri1, seri2], ignore_index=True)
seri

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [132]:
seri.iloc[[4,5,6]]

4    5
5    6
6    7
dtype: int64